version: '3.9'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
        - proxy-network

volumes:
  caddy-data:
  caddy-config:

networks:
  proxy-network:
    external: true